AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app3

  Sample SAM Template for sam-app3

Parameters:
  ENV:
    Type: String
    AllowedValues:
      - main

# Conditions:
#   IsProd: !Equals
#     - !Ref Env
#     - prod
#   IsStage: !Equals
#     - !Ref Env
#     - stage
#   IsDev: !Equals
#     - !Ref Env
#     - dev
    
Globals:
  Function:
    Timeout: 365
    MemorySize: 512
    Runtime: nodejs18.x
    Architectures:
      - x86_64
    # Layers:
    #   - !Ref POCSharedLayer
    # Environment:
    #   Variables:
    #     ENVIRONMENT: !Ref Env

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./helloworld
      Handler: index.handler
      Runtime: nodejs18.x
      Timeout: 365
      MemorySize: 512
      Events:
        HelloWorldApi:
          Type: Api
          Properties:
            Path: /hello
            Method: get
            RestApiId: !Ref POCAPI

  HelloWorldFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${HelloWorldFunction}
      RetentionInDays: 7

  POCAPILogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join ['', ['/aws/apigateway/', !Sub '${AWS::StackName}', '/POC-custom-log-group']]
      RetentionInDays: !If [IsDev, 1, 365] 

  POCAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Env
      CacheClusterEnabled: true
      CacheClusterSize: '0.5'
      MethodSettings:
        - ResourcePath: /*
          HttpMethod: '*'
          CacheTtlInSeconds: 0
          CachingEnabled: false
          CacheDataEncrypted: false
          MetricsEnabled: true
          ThrottlingBurstLimit: !If [IsProd, 5000, 2000]
          ThrottlingRateLimit: !If [IsProd, 3000.0, 1000.0]
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"
      AccessLogSetting:
        DestinationArn: !GetAtt POCAPILogGroup.Arn
        Format: '$context.requestId $context.identity.sourceIp $context.identity.caller $context.identity.user $context.httpMethod $context.resourcePath $context.status $context.integration.latency $context.requestTime $context.protocol $context.responseLength $context.integrationErrorMessage' 

  # POCSharedLayer:
  #   Type: AWS::Serverless::LayerVersion
  #   Properties:
  #     LayerName: !Sub 'POC-SharedLayer-${Env}'
  #     Description: Shared NPM package.
  #     ContentUri: 'layer/'
  #     CompatibleRuntimes:
  #       - nodejs18.x

Outputs:
  POCAPI:
    Description: 'API Gateway endpoint URL'
    Value: !Sub 'https://${AWS::StackName}.execute-api.${AWS::Region}.amazonaws.com/'