name: NodeJS CI/CD

on:
  push:
    branches:
      - main
      - stage
      - dev
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: main
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install and Update AWS SAM CLI
        run: |
          curl -L -o aws-sam-cli-linux-x86_64.zip https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip
          unzip aws-sam-cli-linux-x86_64.zip -d sam-installation
          sudo ./sam-installation/install --update
          sam --version

      - name: Install and Update AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
          aws --version

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      # - name: Setup dependencies
      #   run: npm run setup-deps

      # - name: Run Unit Tests
      #   run: NODE_OPTIONS=--max-old-space-size=8192 npm test

      - name: Create .env file from secrets
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          printenv | grep 'SECRET_KEY_' > .env.${{ secrets.ENV }}
          cat .env.${{ secrets.ENV }}

      - name: Read .env file and construct parameter overrides
        id: construct-params
        run: |
          PARAMS=""
          while IFS= read -r line; do
            IFS='=' read -r key value <<< "$line"
            PARAMS="$PARAMS $key=$value"
          done < .env.${{ secrets.ENV }}
          echo "::set-output name=params::$PARAMS"

      - name: Deploy Backend
        if: github.event_name == 'workflow_dispatch'
        env:
          PARAMS: ${{ steps.construct-params.outputs.params }}
        run: |
          sam deploy \
            --s3-bucket poc-main \
            --stack-name poc-main \
            --capabilities CAPABILITY_IAM \
            --parameter-overrides $PARAMS
